# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  newman:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - uses: matt-ball/newman-action@master
          with:
            apiKey: PMAK-60dadb437e3ccc003fbfa9a7-cdece3db3bed1232b967b31281069717de
            collection: 71c1ec11-7943-434b-8b0b-9f90bf5295e7
            environment: 71c1ec11-7943-434b-8b0b-9f90bf5295e7

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
   
        

  
